apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-redirect
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingress-redirect
spec:
  project: infrastructure
  source:
    path: apps/ingress-redirect
    repoURL: 'https://github.com/SylvainEcuer/univ-argocd.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
