apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "le bédoin"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: "le bédoin"
spec:
  project: infrastructure
  source:
    path: apps/traefik
    repoURL: 'https://github.com/SylvainEcuer/univ-argocd.git'
    helm:
      valueFiles:
      - values.yaml
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
