argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - "unnomprofesionnel.playground.padok.cloud"
      tls:
      - hosts:
        - "unnomprofesionnel.playground.padok.cloud"
        secretName: unnomprofesionnel-playground-padok-cloud-tls
